### ISSUE TITLE
pandas

### ISSUE THREAD

**Issue by kdog0598** [scruwys/and-the-award-goes-to#4]
When i install pandas and numpy via your requiremnts file and run prepare_data.py I get 
`ValueError: numpy.dtype has the wrong size, try recompiling`
But when I install both of them normally through pip i get
`Traceback (most recent call last):`
  `File "prepare_data.py", line 183, in <module>`
   `df['release_month'] = df['release_date'].apply(lambda y: int(y.split('-')[1]))`
  `File "/home/kieran/.local/lib/python2.7/site-packages/pandas/core/series.py", line 3591, in apply`
    `mapped = lib.map_infer(values, f, convert=convert_dtype)`
  `File "pandas/_libs/lib.pyx", line 2217, in pandas._libs.lib.map_infer`
 `File "prepare_data.py", line 183, in <lambda>`
    `df['release_month'] = df['release_date'].apply(lambda y: int(y.split('-')[1]))`
`AttributeError: 'float' object has no attribute 'split'`

Is there a way to fix this?

**Comment by kdog0598** [comment]
I tried it on a clean ubuntu as well with the same issues
EDIT: It appears to be a problem with the data collection because it ran fine when I used the data included in the repository, but failed when using new data.
